### ISSUE TITLE
Entity None (<class 'custom_components.t_smart.climate.TSmartClimateEntity'>) implements HVACMode(s)

### ISSUE THREAD

**Issue by holdestmade** [pdw-mb/tsmart_ha#12]
Getting this in the logs after updating to 2024.2

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate (documentation, issues)
First occurred: 12:54:08 pm (1 occurrences)
Last logged: 12:54:08 pm

Entity None (<class 'custom_components.t_smart.climate.TSmartClimateEntity'>) implements HVACMode(s): off, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/pdw-mb/tsmart_ha/issues

**Comment by pdw-mb** [comment]
Thanks for reporting this.  I've not yet upgraded my HA to 2024.2, but there's a completely untested fix on #13 .

**Comment by holdestmade** [comment]
Hi, tried that and still the same warning in the log. Works ok still though

**Comment by pdw-mb** [comment]
Thanks for checking.  Have now tried it myself, and I think the HA warning is broken.  Have raised https://github.com/home-assistant/core/issues/109865
