### ISSUE TITLE
New Home Assistant log entry

### ISSUE THREAD

**Issue by JeffJakkis** [pdw-mb/tsmart_ha#14]
I'm seeing the following in the HA logs on my system:
WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.t_smart.climate.TSmartClimateEntity'>) implements HVACMode(s): off, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/pdw-mb/tsmart_ha/issues

Home Assistant OS 11.5
Home Assistant Core 2024.2.1

**Comment by pdw-mb** [comment]
Duplicate  of #12

**Comment by JeffJakkis** [comment]
Sorry about that!
