### ISSUE TITLE
Feature Request: Add current temperature as a sensor

### ISSUE THREAD

**Issue by naigle** [pdw-mb/tsmart_ha#2]
Feature Request.

Can you add the current temperature as a sensor?
My intent would be to use this data point to graph temp over time, so I can evaluate general loss and a proxy for water usage.

HA would be able to log and graph but a sensor entity would need to be created.

**Comment by pdw-mb** [comment]
It should be possible to do this already.  The climate entity has a `current_temperature` attribute, so you should be able to set up a template sensor.  See [this thread](https://community.home-assistant.io/t/create-current-temp-entity-from-air-con/391029).

**Comment by naigle** [comment]
Thank you pdw-mb.  
Will Close this and follow your above guidance
