### ISSUE TITLE
Error in HA logs from tsmart integration

### ISSUE THREAD

**Issue by BettySwallocks** [pdw-mb/tsmart_ha#4]
Wondered if this error is common to anyone else using the integration:

"Unexpected error fetching t_smart-6B64E6 data: ValueError('35 is not a valid TSmartMode')"

Happening a lot as it's top of my Sentry error frequency list.

**Comment by BettySwallocks** [comment]
Bit more detail from the Sentry error record:

/config/custom_components/t_smart/coordinator.py in _async_update_data at line 34
In App
        self._error_count = 0
        self._attr_unique_id = device.device_id
    async def _async_update_data(self):
        """Update the state of the device."""
        await self.device.async_get_status()

**Comment by paulwarren-wk** [comment]
I've not seen that, and it's not mentioned in the API docs that I found.  35 is 0x23 in hex, and the docs only have:

* 0x00 - Manual
* 0x01 - Eco
* 0x02 - Smart
* 0x03 - Timer
* 0x04 - Travel
* 0x05 - Boost
* 0x21 - Limited - Warning is active
* 0x22 - Critical - Error is active

The fact that it's one more than the last documented value makes me think that it is a new valid value for the mode.

How recently did you get the device? If you use the TSmart app, what versions do you get on the info screen in the app?

**Comment by pdw-mb** [comment]
I've not seen that, and it's not mentioned in the API docs that I found. 35 is 0x23 in hex, and the docs only have:

0x00 - Manual
0x01 - Eco
0x02 - Smart
0x03 - Timer
0x04 - Travel
0x05 - Boost
0x21 - Limited - Warning is active
0x22 - Critical - Error is active
The fact that it's one more than the last documented value makes me think that it is a new valid value for the mode.

How recently did you get the device? If you use the TSmart app, what versions do you get on the info screen in the app?

**Comment by BettySwallocks** [comment]
Hi, my tsmart device was installed with its parent cylinder at the end of 2022.

The app shows the following versions from 'info':
T-Smart: 2.1.11
Firmware: 1.9.96

**Comment by pdw-mb** [comment]
Meanwhile, I have now seen this issue myself, and I've been meaning to drop the manufacturer a mail to see if they can explain it.

**Comment by BettySwallocks** [comment]
Closing this as I agreed for removal of my Tesla T-Smart with my installer.

**Comment by BettySwallocks** [comment]
Closed.
